---
permalink: administration/reference_parameters_to_set_up_cloning.html 
sidebar: sidebar 
keywords: parameter, snap, creator, server, cloning, operation 
summary: Se necesitan varios parámetros para configurar las operaciones de clonado de Snap Creator Server. 
---
= Parámetros para configurar las operaciones de clonado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necesitan varios parámetros para configurar las operaciones de clonado de Snap Creator Server.

|===
| Parámetro | Ajuste | Descripción 


 a| 
NTAP_VOL_CLONE_RESERVE
 a| 
ninguno
| archivo 


| volumen  a| 
Esta es la garantía de espacio para un volumen clonado.
 a| 
NTAP_LUN_CLONE_RESERVATION



 a| 
verdadero
| falso  a| 
Si se establece en true, se reserva espacio para las LUN clonadas si se selecciona la acción clonelLun. De lo contrario, no se reserva espacio.



 a| 
NTAP_CLONE_IGROUP_MAP
 a| 
 a| 
Especifica el sistema de almacenamiento, el volumen de origen y UN IGROUP. El IGROUP se asigna a LUN clonadas que residen en el volumen de origen o LUN clonados que residen en el clon del volumen (por ejemplo, `controller1:src_volume1/igroup1,src_volume2/igroup1,src_volume3/igroup1;controller2:src_volume1/igroup2,src_volume2/igroup2,src_volume3/igroup2`). *Nota:*

* Los clones de LUN asumen el mismo nombre que su volumen o LUN principal y terminan con _CLONE; es decir, si el volumen se llama myvol, el clon sería myvol_CLONE.
* Los clones de volumen comienzan con cl_ y terminan con -YYYYMMDDHHMMSS.




 a| 
NTAP_CLONE_FOR_BACKUP
 a| 
(Y
| N) 


 a| 
Si está habilitada, se crean clones (volumen y LUN) y se eliminan una vez que se completan las otras operaciones. De lo contrario, los clones se eliminan antes de que completen las operaciones. *Nota:* Si usted está haciendo copias de seguridad de clones en cinta, esto debe ser definido en Y. Si realiza actualizaciones de bases de datos, debe establecerla en N.
 a| 
NTAP_CLONE_SECONDARY
 a| 
(Y



| N)  a| 
Si está habilitada, se crean clones en el destino de SnapMirror una vez que finaliza la actualización de SnapMirror. *Nota:* esta opción debe usarse con NTAP_SNAPMIRROR_USE_SNAPSHOT, NTAP_SNAPMIRROR_WAIT y NTAP_CLONE_SECONDARY_VOLUMES, así como la acción clonVol.
 a| 
NTAP_CLONE_SECONDARY_VOLUMES



 a| 
 a| 
Esta es una asignación de sistemas de almacenamiento primario o secundario y los volúmenes secundarios. Esto es necesario para que Snap Creator pueda encontrar los volúmenes secundarios (por ejemplo, controlador1:controlador1-sec/vol1;controlador1-sec/vol2).
 a| 
NTAP_NUM_VOL_CLONES



 a| 
 a| 
Esta es la cantidad de clones de volúmenes que desea retener. Esto funciona de forma similar a la política de retención de copias de Snapshot. *Nota:* esto sólo funciona para clones de volúmenes que requieran una licencia de FlexClone en la controladora de almacenamiento.
 a| 
NTAP_NFS_EXPORT_HOST



 a| 
IP del host
 a| 
El nombre de host o la dirección IP donde se debe exportar el clon. Este es el host donde se monta el volumen clonado mediante NFS.
 a| 
ACCESO_EXPORTACIÓN_NTAP_NFS



 a| 
raíz
| lectura-escritura | solo lectura 


 a| 
El host especificado en NTAP_NFS_EXPORT_HOST recibe acceso o permiso al volumen clonado.

* raíz
+
Se concede acceso a la raíz.

* solo lectura
+
Se concede acceso de solo lectura.

* lectura-escritura
+
Se concede acceso de lectura/escritura.


 a| 
NTAP_NFS_EXPORT_PERSISTENT
 a| 
verdadero



| falso  a| 
Determina si la exportación NFS es persistente. Si se selecciona TRUE, se exporta el volumen de clonado y se actualiza el archivo /etc/exports en la controladora de almacenamiento.
 a| 
NTAP_CIFS_EXPORT_ENABLE



 a| 
(Y
| N)  a| 
Configuración para compartir un volumen clonado mediante CIFS.

|===