---
permalink: administration/reference_post_commands.html 
sidebar: sidebar 
keywords: snap, creator, server, configuration, post, command, quiescecmde, cmd, ntap, app, post, transfer 
summary: SNAP Creator Server incluye varios comandos POST del archivo de configuración. 
---
= COMANDOS POSTERIORES
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNAP Creator Server incluye varios comandos POST del archivo de configuración.

|===
| Comando | Descripción 


 a| 
POST_APP_ QUIESCECMD ##
 a| 
Este es un comando de inicio de copia de seguridad post-aplicación, donde ## es un número de 01-99.



 a| 
POST_NTAP_CMD ##
 a| 
Este es un comando post, donde ## es un número de 01-99. Esta acción se ejecuta después de que se completan todas las operaciones.



 a| 
POST_APP_UNQUIESCE _CMD ##
 a| 
Este es un comando post-aplicación backup stop, donde ## es un número de 01-99.



 a| 
POST_NTAP_DATA_ TRANSFER_CMD ##
 a| 
Se trata de un comando posterior a la transferencia de datos que se ejecuta después de una transferencia SnapVault o SnapMirror, donde ## es un número del 01 al 99.



 a| 
POST_RESTORE_ CMD ##
 a| 
Se trata de un comando opcional que se puede ejecutar después de completar una restauración interactiva. Le permite interactuar con la aplicación que se restaura. Una vez finalizada la restauración, se puede iniciar la aplicación. *Nota:* esto no es compatible con el plug-in MySQL.



 a| 
POST_CLONE_CREATE_ CMD ##
 a| 
Este es un comando opcional que se puede ejecutar después de que se realicen las operaciones de clonado de ONAPI, donde ## es un número del 01 al 99. Los comandos se utilizan para realizar operaciones como el montaje de sistemas de archivos clonados.

|===