---
permalink: administration/reference_snap_creator_variable_and_parameter_descriptions.html 
sidebar: sidebar 
keywords: snap, creator, built-in, variable, parameter, basic, configuration, description, snap, type, time, action 
summary: SNAP Creator incluye variables integradas y parámetros necesarios en una configuración básica. 
---
= Descripciones de variables y parámetros de Snap Creator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNAP Creator incluye variables integradas y parámetros necesarios en una configuración básica.

|===
| Variables | Descripción 


 a| 
%SNAP_TYPE
 a| 
Se utiliza cuando ejecuta Snap Creator y es su política de retención (diaria, semanal, mensual).



 a| 
%SNAP_TIME
 a| 
La Marca de hora (YYYYYYMMDDhhmmss) utilizada en el nombre de las copias Snapshot para crear un nombre único garantizado para cada copia Snapshot. También se utiliza para asignar nombre a los informes de backup y los registros de transacciones de Sybase.



 a| 
%ACCIÓN
 a| 
La lista de acciones que puede realizar cuando ejecuta Snap Creator: (Backup



| ClonVol | ClonLun 


| arq | restaurar 


| Backupdel | Lista de backupList 


| ClonList | pmsetup 


| ossv)  a| 
%MSG



 a| 
Se utiliza para enviar un mensaje de error a otro programa, como correo electrónico o Tivoli, sólo se puede utilizar con la función SENDTRAP.
 a| 
%USER_DEFINED

|===
En la siguiente tabla se enumeran y se describen los parámetros de Snap Creator utilizados en una configuración básica:

|===


| Parámetro | Ajuste | Descripción 


 a| 
NOMBRE
 a| 
 a| 
Especifica la convención de nomenclatura de copias Snapshot que debe ser única. Las copias Snapshot se eliminan según la convención de nomenclatura.



 a| 
SNAP_TIMESTAMP_ONLY
 a| 
(Y
| N) 


 a| 
Establece la convención de nomenclatura de instantáneas Si se establece en y, las copias snapshot finalizan con YYYYYMMDDHHMMSS. De lo contrario, las nuevas copias snapshot se cambian de nombre para terminar con YYYYYMMDDHHMMSS.
 a| 
VOLÚMENES
 a| 



 a| 
Enumera las controladoras de almacenamiento principal y los volúmenes de los que desea crear una copia Snapshot, por ejemplo:

[listing]
----
controller1:vol1,vol2,vol3;
controller2:vol1;
controller3:vol2,vol3
---- a| 
GRUPOS_VOLÚMENES
 a| 
vol_1,vol_2,vol_n



 a| 
Define varios volúmenes en un único grupo. Varios volúmenes se especifican como un ejemplo de lista separada por comas:

[listing]
----
VOLUMES_01=filer1:vol1,vol2,vol3;filer2:vol1
VOLUMES_02=filer1:vol3,vol4
VOLUMES_03=filer2:vol3,vol4
VOLUME_GROUPS=VOLUMES_01,VOLUMES_02,VOLUMES_03
----

NOTE: VOLUME_GROUPS solo es compatible para las operaciones de backup. Si se establece este parámetro, se ignora el parámetro VOLUMES durante el backup.
 a| 
NTAP_SNAPSHOT_RETENTIONS
 a| 



 a| 
Determina el número de copias Snapshot que se retendrán para un determinado efecto de políticas o ejemplo:

[listing]
----
daily:7,weekly:4,monthly:1
---- a| 
USUARIOS_NTAP
 a| 



 a| 
Muestra los sistemas de almacenamiento y sus nombres de usuario y contraseñas correspondientes.ejemplo:

[listing]
----
controller1:joe/password1;
controller2:bob/password2;
controller3:ken/password3
----

NOTE: La contraseña debe contener al menos dos caracteres.
 a| 
PROTECCIÓN_PWD_NTAP
 a| 
(Y



| N)  a| 
Habilita o deshabilita la protección con contraseña debe cifrar todas las contraseñas (sistema de almacenamiento y aplicaciones o plugins) y guardar las contraseñas cifradas en el archivo de configuración.
 a| 
TRANSPORTE



 a| 
HTTP
| HTTPS  a| 
Permite utilizar HTTP o HTTPS para conectarse a la controladora de almacenamiento**Nota:** HTTPS puede requerir bibliotecas openssl-devel.



 a| 
PUERTO
 a| 
 a| 
Configura el número de puerto que utilizan las controladoras de almacenamiento; normalmente: 80 y 443



 a| 
NÚM_REGISTRO
 a| 
 a| 
Especifica el número de informes .debug y .out que Snap Creator tiene que retener



 a| 
TIPO_CONFIG
 a| 
PLUG-IN
| ESTÁNDAR 


 a| 
Especifica el tipo de configuraciónHere dos tipos de configuraciones: Plug-in y standard. Puede utilizar varias configuraciones de complementos para crear flujos de trabajo complejos de activación y reanudación de los backups.
 a| 
CMODE_CLUSTER_USERS
 a| 



 a| 
(Necesario para Clustered Data ONTAP) enumera los clústeres de Data ONTAP en clúster primario y secundario y sus nombres de usuario y contraseñas correspondientes.ejemplo:

[listing]
----
cluster1:joe/password1;
cluster2:bob/password2
----

NOTE: La contraseña debe contener al menos dos caracteres.
 a| 
CMODE_CLUSTER_NAME
 a| 



 a| 
(Necesario para Clustered Data ONTAP) especifica el nombre del clúster de Data ONTAP principal
 a| 
CMODE_SNAPSHOT_FORCE_DELETE
 a| 
(Y



| N)  a| 
Garantiza la eliminación de las copias Snapshot que deben eliminarse en función de la política de copia de Snapshot en Clustered Data ONTAP, las copias de Snapshot no se eliminan si tienen dependencias, como un clon.
 a| 
LOG_TRACE_ENABLE



 a| 
(Y
| N)  a| 
Habilita o deshabilita el registro de todos los eventos Si está deshabilitado, los objetos de resultados de la solución Administrar ONTAP no se registran.



 a| 
TIEMPO_ESPERA_NTAP
 a| 
Segundos
 a| 
Configura el valor de tiempo de espera para todas las llamadas de la controladora de almacenamiento que gestionan la solución ONTAP; el valor predeterminado es 60 segundos



 a| 
USE_GLOBAL_CONFIG
 a| 
(Y
| N) 


 a| 
Permite utilizar la configuración global para almacenar valores
 a| 
APLICACIONES_FEDERADAS
 a| 



 a| 
Muestra los nombres de configuración y perfil de las aplicaciones federadas en la configuración, por ejemplo:

[listing]
----
databases@db2;databases@oracle
---- a| 
CMODE_SET
 a| 
(Y



| N)  a| 
Define si la configuración es para Clustered Data ONTAP o Data ONTAP en 7-Mode
 a| 
ALLOW_DUPLICATE_SNAME



 a| 
(Y
| N)  a| 
(Opcional) activa o desactiva la capacidad para crear un archivo de configuración con un nombre de instantánea duplicado este parámetro no funcionará con los archivos de configuración globales (Super Global o Profile Global).



 a| 
SNAPCREATOR_MISSEDJOB_RUN
 a| 
(Y
| N) 
|===