---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: Puede personalizar el almacén de claves o certificado predeterminado mediante el comando keytool que está disponible en Windows y UNIX. 
---
= Personalización del almacén de claves predeterminado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar el almacén de claves o certificado predeterminado mediante el comando keytool que está disponible en Windows y UNIX.

Java proporciona el comando keytool. En algunos entornos, es posible que tenga que cambiar al directorio de instalación de Java para ejecutar el comando keytool.

SNAP Creator no admite almacenes de confianza.

. Detenga el agente de Snap Creator.
. Genere un nuevo almacén de claves con un único certificado:
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
Keytool -genkeypair -alias servicekey -keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. Copie el archivo keystore en el directorio scAgent4.3.0/etc/.
. Actualice los parámetros KEYSTORE_FILE=keystore_file y KEYSTORE_PASS=keystore contraseña en el archivo de configuración del agente de Snap Creator (scAgent4.3.0/etc/allowed_Commands.config).
. Inicie el agente de Snap Creator.


*Información relacionada*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Inicio, verificación y detención del agente de Snap Creator en Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Inicio, verificación y detención de Snap Creator Agent en UNIX]
