---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: 'Puede almacenar las credenciales del servidor de Snap Creator (como el nombre de host del servidor o la dirección IP, el puerto, el usuario y la contraseña) para evitar introducir varias veces las credenciales en la interfaz de línea de comandos (CLI). Cuando sea necesario, puede eliminar las credenciales almacenadas.' 
---
= Configurar las credenciales del servidor de Snap Creator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede almacenar las credenciales del servidor de Snap Creator (como el nombre de host del servidor o la dirección IP, el puerto, el usuario y la contraseña) para evitar introducir varias veces las credenciales en la interfaz de línea de comandos (CLI). Cuando sea necesario, puede eliminar las credenciales almacenadas.

El procedimiento para configurar las credenciales del servidor de Snap Creator es el mismo para Windows y UNIX. El siguiente procedimiento utiliza ejemplos del entorno UNIX.

. En el host donde se ha instalado el servidor de Snap Creator, introduzca el siguiente comando en el directorio de instalación de Snap Creator Server:
+
`/install_path/scServer4.3/snapcreator --credentials`

+
Se muestra la siguiente salida, lo que le permite establecer las credenciales predeterminadas para el servidor de Snap Creator:

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. Introduzca la información adecuada para cada entrada.
+
Después de introducir sus datos para la entrada del nombre de configuración, se guardan las credenciales y se muestra el siguiente mensaje: INFO: Las credenciales de la CLI se almacenan correctamente. Las credenciales se almacenan en el archivo snapcreator.alcredenciales en el directorio o carpeta .snapcreatoren el directorio inicial.

. Si desea quitar las credenciales almacenadas, elimine el archivo snapcreator.alcredenciales.

