---
permalink: installation/task_upgrading_the_snap_creator_server_3_6_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 3.6.x, windows 
summary: Puede realizar la actualización directamente desde Snap Creator Server 3.6.x en Windows. 
---
= Actualizar Snap Creator Server 3.6.x en Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar la actualización directamente desde Snap Creator Server 3.6.x en Windows.

* Si tiene algún nombre de usuario de Snap Create que contiene caracteres especiales, debe haber cambiado el nombre de esos usuarios solo con caracteres alfabéticos (a-z, A-Z) antes de realizar la actualización.
* Ha detenido los servicios de Snap Creator (`snapcreatorserverservice` y.. `snapcreatoragentservice`) Antes de realizar una copia de seguridad de los directorios de Snap Creator para garantizar que los datos de la copia de seguridad se han completado.
+
Por ejemplo, puede utilizar el complemento Servicios para detener los servicios:

+
.. Seleccione *Inicio* > *Ejecutar* e introduzca `services.msc`.
.. Busque y seleccione el servicio Snap Creator; a continuación, detenga el servicio. De forma alternativa, puede abrir un símbolo del sistema e introducir los comandos siguientes:


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* Ha realizado un backup de los siguientes directorios y de todos los subdirectorios y archivos asociados, en el directorio del servidor de Snap Creator 3.6.x (C:\Archivos de programa\NetApp\NetApp_Snap_Creator_Framework\scServer3.6.x):
+
** Base de datos de Snap Creator (..\gui\snapcreator)
** Perfiles y archivos de configuración (..\configuraciones)
** Registros (..\logs) *Nota:* no elimine las copias de seguridad de Snap Creator 3.6.x.


* (Opcional) Si se instala Snap Creator Agent en el mismo host que Snap Creator Server, debe realizar una copia de seguridad del archivo agent.conf (C:\Program Files\NetApp\NetApp_Snap_Creator_Framework\scServer3.6.x\config\agent.conf)


Las rutas de acceso proporcionadas en los pasos siguientes hacen referencia a la ruta de instalación predeterminada para Windows. La información de la ruta puede diferir si no se han utilizado los valores predeterminados.

Una vez finalizado el proceso de actualización, tenga en cuenta los siguientes problemas:

* Si la base de datos de Snap Creator que se actualiza contiene algunas tareas marcadas como «'en curso'», el estado permanece igual incluso después de completar el proceso de actualización.
* El administrador predeterminado en la última versión de Snap Creator debe ser un administrador en Snap Creator 3.6.x. Si el usuario 3.6.x no es administrador, la actualización asigna una función de operador al usuario 3.6.x.
+
.. Detenga los servicios de Snap Creator si aún no lo ha hecho.
+
Para obtener información acerca de cómo detener los servicios, consulte los detalles que se proporcionan anteriormente en este tema.

.. Desinstale Snap Creator (para Windows) seleccionando *Inicio* > *programas* > *Snap Creator* > *Desinstalar Snap Creator Framework* de NetApp.
+
Para obtener más detalles, consulte la información sobre cómo desinstalar Snap Creator en Windows.

.. Instale el servidor Snap Creator más reciente.
+
Para obtener detalles, consulte la información sobre la instalación de Snap Creator Server en Windows.

.. Si seleccionó iniciar el servidor de Snap Creator como servicio cuando instaló el último servidor de Snap Creator, detenga el servicio.
+
Para obtener información sobre cómo detener el servicio, consulte los detalles que se proporcionan anteriormente en este tema.

.. Elimine la carpeta más reciente de la base de datos de Snap Creator Server (C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\snapcreator).
.. Copie el directorio de la base de datos Snap Creator 3.6.x con backup en la ubicación más reciente (C:\Archivos de programa\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\snapcreator).
.. Copie los perfiles de Snap Creator 3.6.x y el directorio de configuración con backup en la ubicación más reciente (C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\Configurations).
.. Copie el directorio de registros de Snap Creator 3.6.x con backup en la ubicación más reciente (C:\Archivos de programa\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\logs).
.. Abra un símbolo del sistema y cambie el directorio al subdirectorio del motor en la ruta de instalación de Snap Creator (C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine).
.. Actualice Snap Creator introduciendo el siguiente comando: java -jar snapcreator.jar -upgrade




Una vez completado el proceso de actualización, inicie el servicio Snap Creator Server realizando una de las siguientes acciones:

* Utilice el complemento Servicios e inicie el servicio.
* Introduzca el siguiente comando desde un símbolo del sistema: `sc start snapcreatorserverservice`


Además, debe validar el inicio de la GUI de Snap Creator Framework; para ello, debe navegar hasta el host local del puerto especificado (https://IP_address:gui_port)[].

Debe conectarse mediante HTTPS; de lo contrario, la conexión no se redirige automáticamente a una conexión HTTPS y la GUI no funcionará.

*Información relacionada*

xref:concept_installing_the_snap_creator_server.adoc[Instalar el servidor de Snap Creator]

xref:task_uninstalling_snap_creator_on_windows.adoc[Desinstalar Snap Creator en Windows]
