---
permalink: installation/task_installing_the_snap_creator_agent_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, agent, unix 
summary: 'El agente de Snap Creator se ejecuta en cualquier plataforma de sistemas abiertos (AIX, HP-UX, Linux y Solaris).' 
---
= Instalación del agente de Snap Creator en sistemas basados en UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El agente de Snap Creator se ejecuta en cualquier plataforma de sistemas abiertos (AIX, HP-UX, Linux y Solaris).

Se debe instalar la actualización 72 de JRE 1.8 o una versión posterior. Para obtener detalles, consulte la información de los vínculos relacionados acerca de la instalación de Java en servidores Snap Creator.

La persona que realiza la instalación debe tener suficientes privilegios y acceso.

El puerto predeterminado del agente de Snap Creator es 9090. Utilice netstat o una herramienta similar para comprobar que el puerto de red (9090 o el puerto que desea utilizar) está disponible y no está en uso (por ejemplo, introduzca: `netstat -nap | grep 9090`).

SNAP Creator ya debe descargarse. Para obtener detalles, consulte la información sobre la descarga del software Snap Creator.

Linux se utiliza aquí como plataforma de ejemplo.

. Copie el archivo Snap Creator tar.gz descargado en la ubicación en la que desea instalar Snap Creator Agent.
+

NOTE: Si planea utilizar el complemento IBM Domino, seleccione una ubicación distinta de la carpeta de datos Domino.

+
.. Para crear un subdirectorio, escriba el siguiente comando con el nombre del directorio:
+
[listing]
----
mkdir snap_creator_directory
----
+
[listing]
----
mkdir /SC_41
----
.. Copie el archivo Snap Creator tar.gz en el directorio recién creado introduciendo el comando siguiente:
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. Cambie al directorio en el que se encuentra el archivo .tar de Snap Creator Framework y extraiga el archivo introduciendo los siguientes comandos:
+

NOTE: Según el entorno UNIX, es posible que se requiera descomprimir el archivo antes de introducir el comando tar.

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** SNAP_creator_directory es la ubicación en la que se instalará Snap Creator.
** La versión es la versión actual del paquete de software Snap Creator.
** el sistema operativo es el operativo.
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
Esto extrae tanto el software servidor como el agente. Normalmente, solo se ha configurado el servidor de Snap Creator. Normalmente, los agentes residen en la base de datos o en los servidores de aplicaciones que se van a proteger, como se muestra en el ejemplo siguiente:

+
+

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. Introduzca los siguientes comandos y responda a las indicaciones que se muestran en el ejemplo para configurar el agente de Snap Creator.
+
[listing]
----
cd scAgent*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Agent
Select install option (enter a number or "q" to quit): <Enter 01>

END USER LICENSE AGREEMENT
<...the EULA displays...>

Do you accept the End User License Agreement (y|n): <Enter y>

Enter Snap Creator server port [9090]: <Enter agent port>

INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scAgentrelease-version/engine/etc/agent.properties


INFO: To start scAgent please do the following:

/install_path/scAgentrelease-version/bin/scAgent start
----
. Inicie el agente de Snap Creator:
+
[listing]
----
/install_path/scAgentrelease-version/bin/scAgent start
----
+

NOTE: Para que Snap Creator Agent se ejecute automáticamente en el inicio, agregue el comando start a un script.

+
Los pasos para crear una secuencia de comandos varían ligeramente en función del sistema operativo utilizado y de las preferencias del administrador del sistema que administra el servidor. Generalmente, el comando start del agente de Snap Creator se puede agregar a un archivo que empiece por S9 (por ejemplo, S99scAgent) que se coloca en el subdirectorio /path/to/rc2.d. El subdirectorio rc2.d se encuentra normalmente en /etc/, pero esto puede depender del sistema operativo host y de la configuración particular del servidor. Para obtener más información, consulte la documentación del sistema operativo en uso.

+
Aparece el siguiente mensaje:

+
[listing]
----
Starting scAgent:
    Watchdog: Running
       Agent: Running
----


*Información relacionada*

xref:task_installing_java_on_snap_creator_hosts.adoc[Instalación de Java en hosts de Snap Creator]

xref:task_downloading_the_snap_creator_software.adoc[Descarga del software Snap Creator]
