---
permalink: domino-ops/concept_single_file_restore_in_fc_iscsi_environments.html 
sidebar: sidebar 
keywords: domino, ibm, performing, single-file, restore, single, file, san 
summary: Para las restauraciones de archivos individuales en un entorno SAN, puede utilizar SnapDrive para montar la copia Snapshot en el host del agente de Snap Creator. 
---
= Restaurar archivos individuales en un entorno SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para las restauraciones de archivos individuales en un entorno SAN, puede utilizar SnapDrive para montar la copia Snapshot en el host del agente de Snap Creator. A continuación, puede copiar el archivo que desea restaurar en el directorio de restauración de datos y utilizar una acción personalizada de Snap Creator para completar el procesamiento de la restauración.

*Información relacionada*

xref:task_using_snapdrive_for_windows_to_mount_snapshot_copy.adoc[Uso de SnapDrive para montar una copia Snapshot]

xref:task_copying_files_to_restore_location.adoc[Copia del archivo en el directorio de restauración de datos]

xref:task_running_snap_creator_by_using_the_custom_action.adoc[Usar una acción personalizada de Snap Creator para completar el procesamiento de la restauración]

xref:task_disconnecting_snapshot_copy.adoc[Desconectando la copia snapshot]
